name: Package Labels

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  label-changed-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "testing"
