name: Publish Packages

permissions: write-all

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
        # registry-url: https://npm.pkg.github.com
        # scope: '@near'

    - name: bootstrap dependencies
      run: lerna bootstrap

    - name: Changed packages
      run: lerna changed

    - name: Skip publish
      if: ${{ failure() }}
      run: echo 'No packages changed, skipping publish'

    - name: Publish packages
      run: |
        git config user.email "morgan@near.org"
        git config user.name "CI"
        lerna publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
